<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dasm</string>
		<string>dasm16</string>
	</array>
	<key>name</key>
	<string>DASM-16</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.label.dasm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.label.dasm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^(:)([a-z][a-z_]*)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^\s+(set|add|sub|mul|div|mod|shl|shr|and|bor|xor|ife|ifn|ifg|ifb|mli|dvi|mdi|asr|ifa|ifl|ifu|ifc|adx|sbx|sti|std)\b</string>
			<key>name</key>
			<string>support.function.opcode.basic.dasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^\s+(jsr|int|iag|ias|rfi|iaq|hwn|hwq|hwi)\b</string>
			<key>name</key>
			<string>support.function.opcode.nonbasic.dasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)dat\b</string>
			<key>name</key>
			<string>support.function.data.declaration.dasm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.other.register.dasm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.spValue.dasm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.other.overflow.dasm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(([a-ci-jx-z]|pc|sp)|(pop|peek|push)|o)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b([d-hk-nqrt-w][a-z_]*)|([a-ci-jox-z][a-z_]+)|(s([a-oq-z_][a-z_]*|(p[a-z_]))?)|(p(([abdf-np-tv-z_][a-z_]*)|(c[a-z_]+)|(e(([a-df-z_][a-z_]*)|(e(([a-jl-z_][a-z_]*)|(k[a-z_]+))?))?)|(o(([a-oq-z_][a-z_]*)|(p[a-z_]+))?)|(u(([a-rt-z_][a-z_]*)|(s(([a-gi-z_][a-z_]*)|(h[a-z_]+))?))?))?)\b</string>
			<key>name</key>
			<string>variable.label.dasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;[^$]*</string>
			<key>name</key>
			<string>comment.line.semicolon.dasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^$^"]+"</string>
			<key>name</key>
			<string>string.quoted.double.dasm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hexadecimal.dasm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.dasm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(0(x|X)[\h]+)|([\d]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-</string>
			<key>name</key>
			<string>keyword.operator.dasm</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dasm</string>
	<key>uuid</key>
	<string>28356f7f-d329-42ef-bad9-6ba2de8f7402</string>
</dict>
</plist>
